### ISSUE TITLE
Why does usePathname() from next-intl/client returns  null in 'use client' component

### ISSUE THREAD

**Issue by velychkodmytro20** [amannn/next-intl-example-next-13#3]
Hi, sorry for distracting, my question is why usePathname() always returns in console  `null`  and after that console a current value of my URL?

For example, I just using pathname to see my current value in url when I click on language swithcer component
And every time I see that first value is null, the second is my current ulr
![CleanShot 2023-05-04 at 13 18 25](https://user-images.githubusercontent.com/62553459/236177179-86988dc1-7b9a-4be9-aed9-5a3c1d2c16aa.png)

Because of this behaviour I try to router.push / router.replace to pathname which is null at first time
And get an error every time

Can you please help me? And maybe you have a solution for that
Because usePathname() from next/navigation always works correctly without null at first time

and I use your hook in 'use client' component, after that I use this client component in server components
As I understand i shouldn't get null
version: "next-intl": "2.13.0-beta.2",

BTW after the upgrading the package to 2.13.2 got errors on next build and typescript errow. They were linked with nextConfig in this code

>  const  withNextIntl = require("next-intl/plugin")(
>     // This is the default (also the `src` folder is supported out of the box)
>     "./i18n.ts",
> )

**Comment by amannn** [comment]
Hey! The `usePathname` story is on my list in https://github.com/amannn/next-intl/pull/149, I hope to improve the behaviour here. Can [the routing APIs](https://next-intl-docs.vercel.app/docs/next-13/server-components#routing) help you with your use case?

This repo isn't really for bug reports, I'll close this issue here. If you make an observation that hasn't been mentioned so far, feel free to open an issue or leave a comment in the main repo!
